### PR TITLE
Fix multi-select (issue #41)

### LINKED ISSUE #41: Allow setting a heading style or clearing headings to apply to multiple headings at once
Currently it only applies to cursor, rather than to selection

### PR DESCRIPTION
**Pull request by caffodian**
Fixes #41 - noncollapsed selection -> setting heading types 

Now, we can convert multiple headings at once to be autonumbered (by selecting them)

### CODE REVIEW

File: tests/structuredheadings/formatcombo.js [hunk 1]
```diff
@@ -37,13 +33,9 @@
 
     "if previous heading is autonumber, the new heading is autonumbered": function () {
       var bot = this.editorBot;
-      var ed = this.editor;
       bot.setHtmlWithSelection("<h1 class=\"autonumber autonumber-0\">bar</h1><p>^foo</p>");
-      var formatCombo = ed.ui.get(comboName);
-      assert.areSame(CKEDITOR.TRISTATE_OFF, formatCombo._.state, "check state OFF");
```
Comment (caffodian) [inline tests/structuredheadings/formatcombo.js:43]: assertions on the combo state seem to be prone to random timing issues and flakiness now that firefox is actually used for travis

File: package.json [hunk 2]
```diff
@@ -6,7 +6,7 @@
     "test": "tests"
   },
   "scripts": {
-    "test": "bender run",
+    "test": "bender run -l && bender run -b firefox",
```
Comment (caffodian) [inline package.json:9]: Phantom does some sketchy things around walking in selection ranges (the first heading always seems to go missing), this behaviour does not occur in chrome & firefox.

File: structuredheadings/plugin.js [hunk 3]
```diff
@@ -295,21 +295,42 @@
...
+              }
+            }
+            // apply the correct bulletstyle for all numbered headings
             editor.execCommand("reapplyStyle", value);
+            // set the combo box value
             this.setValue(value, value);
           }
         },
 
+        setAutonumberClassesForHeading: function (heading, value) {
```
Comment (bocribbz) [inline structuredheadings/plugin.js:328]: when this function is called, I see `value` is not set.
what happens then?

File: package.json (hunk 2 above)
Comment (bocribbz) [reply package.json:9]: is this like selenium for js?

File: structuredheadings/plugin.js (hunk 3 above)
Comment (caffodian) [reply structuredheadings/plugin.js:328]: Oops.  Apparently this current style thing doesn't actually matter anymore, but I will fix it

File: package.json (hunk 2 above)
Comment (caffodian) [reply package.json:9]: Bender is CKeditor's testing framework.  it can run using either a headless browser or actual browser.  Unfortunately, phantomjs version that it supports is quite old, and runs into random weird issues around selection, sometimes.  We're just trying to get this stuff working for prototyping and user testing purposes, so I opted to not worry about it

**Comment by bocribbz** [comment]
Looks good to me! 👍
