### PR TITLE
Heading style reset bug

### LINKED ISSUE #65: Fix the weird heading reset
I need to understand what's going on in the video, but this is what Jana says:

> select paragraph, make heading. Then apply numbering. Then, select another paragraph, apply heading. It then resets the numbering

### PR DESCRIPTION
**Pull request by caffodian**
Fixes #65 - Fix a heading style reset bug - new headings do not currently preserve a heading preset, because we don't store it anywhere.  doh

### CODE REVIEW

File: structuredheadings/plugin.js [hunk 1]
```diff
@@ -369,8 +364,10 @@
             var block = elementPath.block;
 
             if (block && isNumbered(editor, block)) {
-              this.setValue(editor.config.autonumberCurrentStyle,
-                        editor.config.autonumberCurrentStyle);
+              this.setValue(
+                self.currentPreset,
+                self.currentPreset
```
Comment (caffodian) [inline structuredheadings/plugin.js]: it didn't make sense to store this on the editor config, and was super annoying to find afterwards

Comment (caffodian) [reply structuredheadings/plugin.js]: now it's stored on the plugin `self/this`

Comment (winhamwr) [reply structuredheadings/plugin.js]: fwiw, I have no guess what this function call does. `setValue` seems very vabue.

File: structuredheadings/plugin.js [hunk 2]
```diff
@@ -227,8 +220,9 @@
  */
 
   CKEDITOR.plugins.add("structuredheadings", {
+    currentPreset: "1.1.1.1.1.",
```
Comment (winhamwr) [inline structuredheadings/plugin.js]: Is this the default for new headings? Maybe `newHeadingDefaultNumbering`?

File: tests/structuredheadings/formatcombo.js [hunk 3]
```diff
@@ -33,23 +38,50 @@
...
-            "<h2 class=\"autonumber autonumber-1\">^foo</h2>",
+            "<h1 class=\"autonumber autonumber-0 autonumber-N\">bar</h1>" +
+            "<h2 class=\"autonumber autonumber-1 autonumber-a\">^foo</h2>",
             bot.htmlWithSelection(),
             "applied h2 block autonumber style"
         );
       });
     },
 
+    "preserves autonumbering levels and preset": function () {
```
Comment (winhamwr) [inline tests/structuredheadings/formatcombo.js]: I like `if previous heading is autonumber, the new heading is autonumbered` as easier-to-understand text, if that's what this is actually testing. I don't know what "preserves autonumbering" means. Seems like it infers the context of "whatever alex thinks should be preserved".

File: tests/structuredheadings/formatcombo.js [hunk 4]
```diff
@@ -33,23 +38,50 @@
       });
     },
 
-    "if previous heading is autonumber, the new heading is autonumbered": function () {
+    "increments autonumbering levels and preset": function () {
```
Comment (winhamwr) [inline tests/structuredheadings/formatcombo.js]: Can you take another crack at this name? What increments autonumbering? Is "preset" a term that's sufficient on its own?

**Comment by winhamwr** [comment]
Does the way this preset variable functions mean that all things converting to headings are going to get the style by default, even if they are in the middle of a set of headings that are styled differently? Seems like the user's desired default is probably closer to "style things based on my surroundings", right?

File: structuredheadings/plugin.js (hunk 1 above)
Comment (caffodian) [reply structuredheadings/plugin.js]: It is actually a combobox function.  set the displayed value / actual value

File: tests/structuredheadings/formatcombo.js (hunk 4 above)
Comment (caffodian) [reply tests/structuredheadings/formatcombo.js]: Preset should probably be something like numberingScheme now that I think about it

File: structuredheadings/plugin.js (hunk 2 above)
Comment (caffodian) [reply structuredheadings/plugin.js]: This is the numbering scheme set on the current document, which determines which scheme new headings take, and should match the pattern of the existing headings

**Comment by caffodian** [comment]
> Does the way this preset variable functions mean that all things converting to headings are going to get the style by default, even if they are in the middle of a set of headings that are styled differently? Seems like the user's desired default is probably closer to "style things based on my surroundings", right?

I don't really get this question, so I'll just start from scratch.  I think the answer is yes.  

So the way we've intended is that, unless you've cleared numbering, new headings should just pick up the existing numbering scheme.

Currently, that is bugged, and every new heading has a side effect of resetting the numbering scheme to  1.1.1.1.1. (the default).  Then you have to re-apply a numbering scheme, which goes back and redoes all your numbered headings.  

We didn't intend to support > 1 numbering scheme per document (that would be madness) but we do allow restarting & clearing.  

This ticket fixes things such that the plugin:

1)  actually stores a state variable with the current numbering scheme
2)  uses that to apply the correct css classes to new headings

Next up is, given an existing autonumbered document, discover the numbering scheme based on the headings in the document.

File: tests/structuredheadings/formatcombo.js (hunk 3 above)
Comment (caffodian) [reply tests/structuredheadings/formatcombo.js]: This should be, more accurately:  

"when creating a new autonumbered heading of the same level, the level and numbering scheme css classes are kept"

File: tests/structuredheadings/formatcombo.js (hunk 4 above)
Comment (caffodian) [reply tests/structuredheadings/formatcombo.js]: This should be, more accurately:  

"when creating a new autonumbered heading of the next level, the level is incremented and the  numbering scheme matches the expected class for the next level"
