### PR TITLE
Fix #50 - Undo doesn't work for many of the structured headings functionality

### LINKED ISSUE #50: Dropdown change events may not be working properly
We have an autosave plugin that hooks into CKEditor, however, it doesn't appear to detect dirtiness when headings are applied or unapplied

### PR DESCRIPTION
**Pull request by caffodian**
Notably, it's completely busted for tab/shift tab, as well as any of the dropdown options.

### CODE REVIEW

**Comment by caffodian** [comment]
An interesting learning - execCommand seems to implicitly take care of snapshotting.  So one future refactor could be ensuring all the dropdown options are represented as commands consistently, (some are, some are not)

File: structuredheadings/plugin.js [hunk 1]
```diff
@@ -331,10 +335,11 @@
           }
 
           // apply the correct bulletstyle for all numbered headings
+          editor.fire("lockSnapshot");
           editor.execCommand("reapplyStyle", value);
           // set the combo box value
           this.setValue(value, value);
-
+          editor.fire("unlockSnapshot");
```
Comment (caffodian) [inline structuredheadings/plugin.js:345]: This is a shady way to avoid further refactoring for now.  the execCommand also creates snapshots, so without locking & unlocking, we end up going from:

unnumbered -> has some of the numbering classes set up -> has all the numbering classes setup, 

the lock ends up combining the latter two snapshots for now.

File: structuredheadings/plugin.js [hunk 2]
```diff
@@ -216,6 +216,7 @@
         },
 
         onClick: function (value) {
+          editor.fire("saveSnapshot");
```
Comment (caffodian) [inline structuredheadings/plugin.js:219]: this onclick is for the headings dropdown

File: structuredheadings/plugin.js [hunk 3]
```diff
@@ -305,10 +307,12 @@
           setLevel(editor, heading);
           setCurrentStyle(editor, heading, value);
         },
+        onClick: function (value) {  // eslint-disable-line max-statements
+          editor.fire("saveSnapshot");
```
Comment (caffodian) [inline structuredheadings/plugin.js:311]: the styles dropdown

File: tests/structuredheadings/formatcombo.js [hunk 4]
```diff
@@ -142,6 +144,77 @@
             "applied pre to h1"
         );
       });
+    },
+
+    "autonumbered heading is undoable": function () {
```
Comment (caffodian) [inline tests/structuredheadings/formatcombo.js:149]: I first made separate tests for undo, but then started just adding undo checks in where it made sense.  This is the separate tests case

File: structuredheadings/plugin.js [hunk 5]
```diff
@@ -305,10 +307,12 @@
           setLevel(editor, heading);
           setCurrentStyle(editor, heading, value);
         },
+        onClick: function (value) {  // eslint-disable-line max-statements
```
Comment (winhamwr) [inline structuredheadings/plugin.js:310]: What's up with the max-statements limit?

File: structuredheadings/plugin.js (hunk 3 above)
Comment (winhamwr) [reply structuredheadings/plugin.js:311]: Why do we need to save a snapshot both before and after? That doesn't seem right. Isn't the pattern to save a snapshot after you do some work (which is what execCommand probably does automatically)?

File: structuredheadings/plugin.js (hunk 1 above)
Comment (winhamwr) [reply structuredheadings/plugin.js:345]: Can you add this is a comment within the code? Future-me looking at this code would be very confused by the lock/unlock around the execCommand without this context.

File: tests/structuredheadings/clearnumberingstyle.js [hunk 6]
```diff
@@ -1,5 +1,7 @@
+/* eslint-disable */
 /* bender-tags: editor,unit */
-/* bender-ckeditor-plugins: wysiwygarea,structuredheadings,toolbar,basicstyles,dialog,richcombo */
+/* bender-ckeditor-plugins: wysiwygarea,structuredheadings,toolbar,basicstyles,dialog,richcombo,undo */
+/* eslint-enable */
```
Comment (winhamwr) [inline tests/structuredheadings/clearnumberingstyle.js:4]: Why the need to enable/disable eslint?

File: tests/structuredheadings/clearnumberingstyle.js [hunk 7]
```diff
@@ -43,6 +54,15 @@
             bot.getData(),
             "cleared styling from headings"
         );
+
+        bot.execCommand("undo");
+        // this is weird, but the selection API returns the extra (internal) paragraphs
+        // that are created to normalize the selection here
+        assert.areSame(
+          initialHtmlWithSelection.substring(1, initialHtmlWithSelection.length - 1),
```
Comment (winhamwr) [inline tests/structuredheadings/clearnumberingstyle.js]: Can we assign this value to a variable before using it? It's not clear to me why we need to do this substring, even with the comment above.

File: tests/structuredheadings/clearnumberingstyle.js (hunk 6 above)
Comment (caffodian) [reply tests/structuredheadings/clearnumberingstyle.js:4]: it chokes on things in the bender comment, like the excessive line mostly.

I guess i could have just disabled the one rule in block form.  the same line ignore doesn't work because it's already a comment.

File: structuredheadings/plugin.js (hunk 5 above)
Comment (caffodian) [reply structuredheadings/plugin.js:310]: Our preset config has it set at 15.  This is 16 due to the snapshotting needs.  I started refactoring and felt like I was getting too far away from just fixing the immediate issues

**Review by winhamwr — APPROVED** [review]

File: structuredheadings/plugin.js (hunk 3 above)
Comment (caffodian) [reply structuredheadings/plugin.js:311]: I was unsure about this, but it looks like the built in style combo does this.  I assume it's for if you have some pending non-snapshotted changes before you click the dropdown.  It appears that if you truly do commit duplicate snapshots, they don't actually get created (or get merged somehow)
